baseURL: ""
languageCode: en-us
title: Meet Shah
theme: PaperMod

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog!
  socialIcons:
    - name: facebook
      url: "https://facebook.com"
    - name: twitter
      url: "https://twitter.com"
    - name: github
      url: "https://github.com"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  comments: true
